fix initialization of binary and soap formatters for mono remoting
git-svn-id: svn://svn.code.sf.net/p/ifolder/code/trunk@123 db2431b9-df06-0410-971c-a38ea9a75485

diff --git a/simias/src/Sync/t1 b/simias/src/Sync/t1
--- a/simias/src/Sync/t1
+++ b/simias/src/Sync/t1
@@ -96,6 +96,16 @@ mono --debug SyncCmd.exe -s tmpClientData localsync tmpClientData/testFolder tmp
 RETVAL=$?
 if [ $RETVAL -ne 0 ]; then printf "FAILED: localsync 3 returned %s\n" $RETVAL; exit $RETVAL; fi
 
+# localsync
+mono --debug SyncCmd.exe -s tmpClientData localsync tmpClientData/testFolder tmpServerData
+RETVAL=$?
+if [ $RETVAL -ne 0 ]; then printf "FAILED: localsync 3 returned %s\n" $RETVAL; exit $RETVAL; fi
+
+# localsync
+mono --debug SyncCmd.exe -s tmpClientData localsync tmpClientData/testFolder tmpServerData
+RETVAL=$?
+if [ $RETVAL -ne 0 ]; then printf "FAILED: localsync 3 returned %s\n" $RETVAL; exit $RETVAL; fi
+
 diff tmpClientData/testFolder tmpServerData/testFolder
 RETVAL=$?
 if [ $RETVAL -ne 0 ]; then printf "FAILED: diff of testFolder after localsync 3 returned %s\n" $RETVAL; exit $RETVAL; fi 
