Added an error message if VS.NET (devenv.exe) is not available to build MSI and MSM packages
git-svn-id: svn://svn.code.sf.net/p/ifolder/code/trunk@617 db2431b9-df06-0410-971c-a38ea9a75485

diff --git a/simias/package/windows/Makefile.am b/simias/package/windows/Makefile.am
--- a/simias/package/windows/Makefile.am
+++ b/simias/package/windows/Makefile.am
@@ -28,13 +28,16 @@ MSM_FILE = $(PACKAGE)-$(VERSION)-$(RELEASE).msm
 MSI_LOG_FILE = devenv-simias-msi.log
 MSM_LOG_FILE = devenv-simias-msm.log
 
-.PHONY: package package-clean package-install package-uninstall simias
+.PHONY: package package-clean package-install package-uninstall simias devenv
 
 all clean:
 
 package: $(MSI_FILE)
 
-$(MSI_FILE): $(MSM_FILE) simias-install.sln simias-msi/simias-msi.vdproj
+devenv:
+	@if ! test -x "$(VSINSTALLDIR)/devenv.exe"; then echo "Error: Microsoft Visual Studio .NET is currently required to build MSI and MSM packages"; exit 1; fi
+
+$(MSI_FILE): devenv $(MSM_FILE) simias-install.sln simias-msi/simias-msi.vdproj
 	@rm -f $(MSI_LOG_FILE) $@
 	@CMD='"$(VSINSTALLDIR)/devenv.exe" simias-install.sln /build $(DEVENV_CONFIGURATION) /project simias-msi /out $(MSI_LOG_FILE)'; \
 	echo $$CMD; \
@@ -45,7 +48,7 @@ $(MSI_FILE): $(MSM_FILE) simias-install.sln simias-msi/simias-msi.vdproj
 		grep -a "ERROR:" $(MSI_LOG_FILE); \
 	fi
 
-$(MSM_FILE): simias simias-install.sln simias-msm/simias-msm.vdproj
+$(MSM_FILE): devenv simias simias-install.sln simias-msm/simias-msm.vdproj
 	@rm -f $(MSM_LOG_FILE) $@
 	@CMD='"$(VSINSTALLDIR)/devenv.exe" simias-install.sln /build $(DEVENV_CONFIGURATION) /project simias-msm /out $(MSM_LOG_FILE)'; \
 	echo $$CMD; \
