Modified behavior of clean, distclean, and maintainer-clean targets
git-svn-id: svn://svn.code.sf.net/p/ifolder/code/trunk@1006 db2431b9-df06-0410-971c-a38ea9a75485

diff --git a/addressbook/package/windows/Makefile.am b/addressbook/package/windows/Makefile.am
--- a/addressbook/package/windows/Makefile.am
+++ b/addressbook/package/windows/Makefile.am
@@ -20,22 +20,37 @@
 #  Author: Paul Thomas <pthomas@novell.com>
 #
 #######################################################################
-EXTRA_DIST = $(srcdir)/Makefile.am $(srcdir)/addressbook-install.sln $(srcdir)/addressbook-msi/addressbook-msi.vdproj $(srcdir)/addressbook-msm/addressbook-msm.vdproj
+EXTRA_DIST = $(srcdir)/Makefile.am $(srcdir)/addressbook-install.sln $(srcdir)/addressbook-msi/addressbook-msi.vdproj $(srcdir)/addressbook-msm/addressbook-msm.vdproj $(srcdir)/addressbook-sdk-msi/addressbook-sdk-msi.vdproj $(srcdir)/addressbook-sdk-msm/addressbook-sdk-msm.vdproj
 
 RELEASE = 1
-MSI_FILE = $(PACKAGE)-$(VERSION)-$(RELEASE).msi
-MSM_FILE = $(PACKAGE)-$(VERSION)-$(RELEASE).msm
-MSI_LOG_FILE = devenv-addressbook-msi.log
-MSM_LOG_FILE = devenv-addressbook-msm.log
+MSI_FILE     = $(PACKAGE)-$(VERSION)-$(RELEASE).msi
+MSM_FILE     = $(PACKAGE)-$(VERSION)-$(RELEASE).msm
+SDK_MSI_FILE = $(PACKAGE)-sdk-$(VERSION)-$(RELEASE).msi
+SDK_MSM_FILE = $(PACKAGE)-sdk-$(VERSION)-$(RELEASE).msm
+MSI_LOG_FILE     = devenv-addressbook-msi.log
+MSM_LOG_FILE     = devenv-addressbook-msm.log
+SDK_MSI_LOG_FILE = devenv-addressbook-sdk-msi.log
+SDK_MSM_LOG_FILE = devenv-addressbook-sdk-msm.log
 
-.PHONY: package package-clean package-install package-uninstall addressbook devenv
+.PHONY: package package-sdk package-clean package-install package-uninstall addressbook addressbook-doc devenv
 
 all clean:
 
 package: $(MSI_FILE)
 
+package-sdk: package $(SDK_MSI_FILE)
+
+addressbook:
+	make -C ../.. all
+	
+addressbook-doc:
+	make -C ../../doc all
+	
 devenv:
 	@if ! test -x "$(VSINSTALLDIR)/devenv.exe"; then echo "Error: Microsoft Visual Studio .NET is currently required to build MSI and MSM packages"; exit 1; fi
+
+ndoc:
+	@if ! test -x "$(NDOC_CMD)"; then echo "Error: You must configure using --with-ndoc-path to build SDK packages"; exit 1; fi
 
 $(MSI_FILE): devenv $(MSM_FILE) addressbook-install.sln addressbook-msi/addressbook-msi.vdproj
 	@rm -f $(MSI_LOG_FILE) $@
@@ -59,29 +74,34 @@ $(MSM_FILE): devenv addressbook addressbook-install.sln addressbook-msm/addressb
 		grep -a "ERROR:" $(MSM_LOG_FILE); \
 	fi
 
-addressbook:
-	make -C ../.. all
-	
-package-install: $(MSI_FILE)
-	@CMD='msiexec /i $(MSI_FILE) /qb+ /L* install-msi.log'; \
+$(SDK_MSI_FILE): devenv $(SDK_MSM_FILE) addressbook-install.sln addressbook-sdk-msi/addressbook-sdk-msi.vdproj
+	@rm -f $(SDK_MSI_LOG_FILE) $@
+	@CMD='"$(VSINSTALLDIR)/devenv.exe" addressbook-install.sln /build $(DEVENV_CONFIGURATION) /project addressbook-sdk-msi /out $(SDK_MSI_LOG_FILE)'; \
 	echo $$CMD; \
-	if ! eval $$CMD; then \
-		grep -a "ERROR:" install-msi.log; \
+	if eval $$CMD; then \
+		mv addressbook-sdk-msi/$(DEVENV_CONFIGURATION)/addressbook-sdk.msi .; \
+		ln addressbook-sdk.msi $@; \
+	else \
+		grep -a "ERROR:" $(SDK_MSI_LOG_FILE); \
 	fi
-	
-package-uninstall:
-	@CMD='msiexec /x $(MSI_FILE) /qb+ /L* uninstall-msi.log'; \
+
+$(SDK_MSM_FILE): devenv ndoc $(MSM_FILE) addressbook-doc addressbook-install.sln addressbook-sdk-msm/addressbook-sdk-msm.vdproj
+	@rm -f $(SDK_MSM_LOG_FILE) $@
+	@CMD='"$(VSINSTALLDIR)/devenv.exe" addressbook-install.sln /build $(DEVENV_CONFIGURATION) /project addressbook-sdk-msm /out $(SDK_MSM_LOG_FILE)'; \
 	echo $$CMD; \
-	if ! eval $$CMD; then \
-		grep -a "ERROR:" uninstall-msi.log; \
+	if eval $$CMD; then \
+		mv addressbook-sdk-msm/$(DEVENV_CONFIGURATION)/addressbook-sdk.msm .; \
+		ln addressbook-sdk.msm $@; \
+	else \
+		grep -a "ERROR:" $(SDK_MSM_LOG_FILE); \
 	fi
 
 package-clean clean-local:
 	rm -rf  *.msi *.msm Release Debug */Release */Debug *.log *.suo
 
 distclean-local: package-clean
-	rm -f Makefile addressbook.spec
+	rm -f addressbook.spec
 
 maintainer-clean-local:
-	rm -f Makefile.in
+	rm -rf $(COMMON_MAINTAINER_CLEAN_FILES)
 
diff --git a/ifolder/package/windows/Makefile.am b/ifolder/package/windows/Makefile.am
--- a/ifolder/package/windows/Makefile.am
+++ b/ifolder/package/windows/Makefile.am
@@ -22,11 +22,17 @@
 #######################################################################
 ShutdowniFolder_CSFILES = $(srcdir)/ShutdowniFolder/ShutdowniFolder.cs $(srcdir)/ShutdowniFolder/AssemblyInfo.cs
 
-EXTRA_DIST = $(srcdir)/Makefile.am $(srcdir)/ifolder-install.sln $(srcdir)/ifolder-msi/ifolder-msi.vdproj $(srcdir)/ShutdowniFolder/ShutdowniFolder.csproj $(ShutdowniFolder_CSFILES) $(srcdir)/ShutdowniFolder/App.ico
+EXTRA_DIST = $(srcdir)/Makefile.am $(srcdir)/ifolder-install.sln $(srcdir)/ifolder-msi/ifolder-msi.vdproj $(srcdir)/ifolder-msm/ifolder-msm.vdproj $(srcdir)/ifolder-sdk-msi/ifolder-sdk-msi.vdproj $(srcdir)/ifolder-sdk-msm/ifolder-sdk-msm.vdproj $(srcdir)/ShutdowniFolder/ShutdowniFolder.csproj $(ShutdowniFolder_CSFILES) $(srcdir)/ShutdowniFolder/App.ico
 
 RELEASE = 1
 MSI_FILE = $(PACKAGE)-$(VERSION)-$(RELEASE).msi
+MSM_FILE     = $(PACKAGE)-$(VERSION)-$(RELEASE).msm
+SDK_MSI_FILE = $(PACKAGE)-sdk-$(VERSION)-$(RELEASE).msi
+SDK_MSM_FILE = $(PACKAGE)-sdk-$(VERSION)-$(RELEASE).msm
 MSI_LOG_FILE = devenv-ifolder-msi.log
+MSM_LOG_FILE     = devenv-ifolder-msm.log
+SDK_MSI_LOG_FILE = devenv-ifolder-sdk-msi.log
+SDK_MSM_LOG_FILE = devenv-ifolder-sdk-msm.log
 
 .PHONY: package package-clean package-install package-uninstall ifolder devenv
 
@@ -34,10 +40,21 @@ all clean:
 
 package: $(MSI_FILE)
 
-devenv:
-	@if ! test -x "$(VSINSTALLDIR)/devenv.exe"; then echo "Error: Microsoft Visual Studio .NET is currently required to build MSI packages"; exit 1; fi
+package-sdk: package $(SDK_MSI_FILE)
 
-$(MSI_FILE): devenv ifolder ifolder-install.sln ifolder-msi/ifolder-msi.vdproj ShutdowniFolder/ShutdowniFolder.exe
+ifolder:
+	make -C ../.. all
+	
+ifolder-doc:
+	make -C ../../doc all
+	
+devenv:
+	@if ! test -x "$(VSINSTALLDIR)/devenv.exe"; then echo "Error: Microsoft Visual Studio .NET is currently required to build MSI and MSM packages"; exit 1; fi
+
+ndoc:
+	@if ! test -x "$(NDOC_CMD)"; then echo "Error: You must configure using --with-ndoc-path to build SDK packages"; exit 1; fi
+
+$(MSI_FILE): devenv $(MSM_FILE) ifolder-install.sln ifolder-msi/ifolder-msi.vdproj ShutdowniFolder/ShutdowniFolder.exe
 	@rm -f $(MSI_LOG_FILE) $@
 	@CMD='"$(VSINSTALLDIR)/devenv.exe" ifolder-install.sln /build $(DEVENV_CONFIGURATION) /project ifolder-msi /out $(MSI_LOG_FILE)'; \
 	echo $$CMD; \
@@ -48,32 +65,50 @@ $(MSI_FILE): devenv ifolder ifolder-install.sln ifolder-msi/ifolder-msi.vdproj S
 		grep -a "ERROR:" $(MSI_LOG_FILE); \
 	fi
 
-ifolder:
-	make -C ../.. all
-	
+$(MSM_FILE): devenv ifolder ifolder-install.sln ifolder-msm/ifolder-msm.vdproj
+	@rm -f $(MSM_LOG_FILE) $@
+	@CMD='"$(VSINSTALLDIR)/devenv.exe" ifolder-install.sln /build $(DEVENV_CONFIGURATION) /project ifolder-msm /out $(MSM_LOG_FILE)'; \
+	echo $$CMD; \
+	if eval $$CMD; then \
+		mv ifolder-msm/$(DEVENV_CONFIGURATION)/ifolder.msm .; \
+		ln ifolder.msm $@; \
+	else \
+		grep -a "ERROR:" $(MSM_LOG_FILE); \
+	fi
+
+$(SDK_MSI_FILE): devenv $(SDK_MSM_FILE) ifolder-install.sln ifolder-sdk-msi/ifolder-sdk-msi.vdproj
+	@rm -f $(SDK_MSI_LOG_FILE) $@
+	@CMD='"$(VSINSTALLDIR)/devenv.exe" ifolder-install.sln /build $(DEVENV_CONFIGURATION) /project ifolder-sdk-msi /out $(SDK_MSI_LOG_FILE)'; \
+	echo $$CMD; \
+	if eval $$CMD; then \
+		mv ifolder-sdk-msi/$(DEVENV_CONFIGURATION)/ifolder-sdk.msi .; \
+		ln ifolder-sdk.msi $@; \
+	else \
+		grep -a "ERROR:" $(SDK_MSI_LOG_FILE); \
+	fi
+
+$(SDK_MSM_FILE): devenv ndoc $(MSM_FILE) ifolder-doc ifolder-install.sln ifolder-sdk-msm/ifolder-sdk-msm.vdproj
+	@rm -f $(SDK_MSM_LOG_FILE) $@
+	@CMD='"$(VSINSTALLDIR)/devenv.exe" ifolder-install.sln /build $(DEVENV_CONFIGURATION) /project ifolder-sdk-msm /out $(SDK_MSM_LOG_FILE)'; \
+	echo $$CMD; \
+	if eval $$CMD; then \
+		mv ifolder-sdk-msm/$(DEVENV_CONFIGURATION)/ifolder-sdk.msm .; \
+		ln ifolder-sdk.msm $@; \
+	else \
+		grep -a "ERROR:" $(SDK_MSM_LOG_FILE); \
+	fi
+
 ShutdowniFolder/ShutdowniFolder.exe: ShutdowniFolder/ShutdowniFolder.csproj $(ShutdowniFolder_CSFILES)
 	"$(VSINSTALLDIR)/devenv.exe" ifolder-install.sln /build $(DEVENV_CONFIGURATION) /project ShutdowniFolder /out devenv-shutdown-msi.log
 
-package-install: $(MSI_FILE)
-	@CMD='msiexec /i $(MSI_FILE) /qb+ /L* install-msi.log'; \
-	echo $$CMD; \
-	if ! eval $$CMD; then \
-		grep -a "ERROR:" install-msi.log; \
-	fi
-	
-package-uninstall:
-	@CMD='msiexec /x $(MSI_FILE) /qb+ /L* uninstall-msi.log'; \
-	echo $$CMD; \
-	if ! eval $$CMD; then \
-		grep -a "ERROR:" uninstall-msi.log; \
-	fi
 
 package-clean clean-local:
-	rm -rf *.msi Release Debug */Release */Debug *.log *.suo
+	rm -rf  *.msi *.msm Release Debug */Release */Debug *.log *.suo
 	cd ShutdowniFolder; rm -rf ShutdowniFolder.exe bin obj *.log *.suo *.csproj.user
 
 distclean-local: package-clean
+	rm -f ifolder.spec
 
 maintainer-clean-local:
-	rm -f Makefile.in
+	rm -rf $(COMMON_MAINTAINER_CLEAN_FILES)
 
diff --git a/simias/package/windows/Makefile.am b/simias/package/windows/Makefile.am
--- a/simias/package/windows/Makefile.am
+++ b/simias/package/windows/Makefile.am
@@ -20,22 +20,37 @@
 #  Author: Paul Thomas <pthomas@novell.com>
 #
 #######################################################################
-EXTRA_DIST = $(srcdir)/Makefile.am $(srcdir)/simias-install.sln $(srcdir)/simias-msi/simias-msi.vdproj $(srcdir)/simias-msm/simias-msm.vdproj
+EXTRA_DIST = $(srcdir)/Makefile.am $(srcdir)/simias-install.sln $(srcdir)/simias-msi/simias-msi.vdproj $(srcdir)/simias-msm/simias-msm.vdproj $(srcdir)/simias-sdk-msi/simias-sdk-msi.vdproj $(srcdir)/simias-sdk-msm/simias-sdk-msm.vdproj
 
 RELEASE = 1
-MSI_FILE = $(PACKAGE)-$(VERSION)-$(RELEASE).msi
-MSM_FILE = $(PACKAGE)-$(VERSION)-$(RELEASE).msm
-MSI_LOG_FILE = devenv-simias-msi.log
-MSM_LOG_FILE = devenv-simias-msm.log
+MSI_FILE     = $(PACKAGE)-$(VERSION)-$(RELEASE).msi
+MSM_FILE     = $(PACKAGE)-$(VERSION)-$(RELEASE).msm
+SDK_MSI_FILE = $(PACKAGE)-sdk-$(VERSION)-$(RELEASE).msi
+SDK_MSM_FILE = $(PACKAGE)-sdk-$(VERSION)-$(RELEASE).msm
+MSI_LOG_FILE     = devenv-simias-msi.log
+MSM_LOG_FILE     = devenv-simias-msm.log
+SDK_MSI_LOG_FILE = devenv-simias-sdk-msi.log
+SDK_MSM_LOG_FILE = devenv-simias-sdk-msm.log
 
-.PHONY: package package-clean package-install package-uninstall simias devenv
+.PHONY: package package-sdk package-clean package-install package-uninstall simias simias-doc devenv
 
 all clean:
 
 package: $(MSI_FILE)
 
+package-sdk: package $(SDK_MSI_FILE)
+
+simias:
+	make -C ../.. all
+	
+simias-doc:
+	make -C ../../doc all
+	
 devenv:
 	@if ! test -x "$(VSINSTALLDIR)/devenv.exe"; then echo "Error: Microsoft Visual Studio .NET is currently required to build MSI and MSM packages"; exit 1; fi
+
+ndoc:
+	@if ! test -x "$(NDOC_CMD)"; then echo "Error: You must configure using --with-ndoc-path to build SDK packages"; exit 1; fi
 
 $(MSI_FILE): devenv $(MSM_FILE) simias-install.sln simias-msi/simias-msi.vdproj
 	@rm -f $(MSI_LOG_FILE) $@
@@ -59,29 +74,34 @@ $(MSM_FILE): devenv simias simias-install.sln simias-msm/simias-msm.vdproj
 		grep -a "ERROR:" $(MSM_LOG_FILE); \
 	fi
 
-simias:
-	make -C ../.. all
-	
-package-install: $(MSI_FILE)
-	@CMD='msiexec /i $(MSI_FILE) /qb+ /L* install-msi.log'; \
+$(SDK_MSI_FILE): devenv $(SDK_MSM_FILE) simias-install.sln simias-sdk-msi/simias-sdk-msi.vdproj
+	@rm -f $(SDK_MSI_LOG_FILE) $@
+	@CMD='"$(VSINSTALLDIR)/devenv.exe" simias-install.sln /build $(DEVENV_CONFIGURATION) /project simias-sdk-msi /out $(SDK_MSI_LOG_FILE)'; \
 	echo $$CMD; \
-	if ! eval $$CMD; then \
-		grep -a "ERROR:" install-msi.log; \
+	if eval $$CMD; then \
+		mv simias-sdk-msi/$(DEVENV_CONFIGURATION)/simias-sdk.msi .; \
+		ln simias-sdk.msi $@; \
+	else \
+		grep -a "ERROR:" $(SDK_MSI_LOG_FILE); \
 	fi
-	
-package-uninstall:
-	@CMD='msiexec /x $(MSI_FILE) /qb+ /L* uninstall-msi.log'; \
+
+$(SDK_MSM_FILE): devenv ndoc $(MSM_FILE) simias-doc simias-install.sln simias-sdk-msm/simias-sdk-msm.vdproj
+	@rm -f $(SDK_MSM_LOG_FILE) $@
+	@CMD='"$(VSINSTALLDIR)/devenv.exe" simias-install.sln /build $(DEVENV_CONFIGURATION) /project simias-sdk-msm /out $(SDK_MSM_LOG_FILE)'; \
 	echo $$CMD; \
-	if ! eval $$CMD; then \
-		grep -a "ERROR:" uninstall-msi.log; \
+	if eval $$CMD; then \
+		mv simias-sdk-msm/$(DEVENV_CONFIGURATION)/simias-sdk.msm .; \
+		ln simias-sdk.msm $@; \
+	else \
+		grep -a "ERROR:" $(SDK_MSM_LOG_FILE); \
 	fi
 
 package-clean clean-local:
 	rm -rf  *.msi *.msm Release Debug */Release */Debug *.log *.suo
 
 distclean-local: package-clean
-	rm -f Makefile simias.spec
+	rm -f simias.spec simias-sdk.spec
 
 maintainer-clean-local:
-	rm -f Makefile.in
+	rm -rf $(COMMON_MAINTAINER_CLEAN_FILES)
 
