Added an error message if VS.NET (devenv.exe) is not available to build MSI and MSM packages
git-svn-id: svn://svn.code.sf.net/p/ifolder/code/trunk@620 db2431b9-df06-0410-971c-a38ea9a75485

diff --git a/addressbook/package/windows/Makefile.am b/addressbook/package/windows/Makefile.am
--- a/addressbook/package/windows/Makefile.am
+++ b/addressbook/package/windows/Makefile.am
@@ -28,13 +28,16 @@ MSM_FILE = $(PACKAGE)-$(VERSION)-$(RELEASE).msm
 MSI_LOG_FILE = devenv-addressbook-msi.log
 MSM_LOG_FILE = devenv-addressbook-msm.log
 
-.PHONY: package package-clean package-install package-uninstall addressbook
+.PHONY: package package-clean package-install package-uninstall addressbook devenv
 
 all clean:
 
 package: $(MSI_FILE)
 
-$(MSI_FILE): $(MSM_FILE) addressbook-install.sln addressbook-msi/addressbook-msi.vdproj
+devenv:
+	@if ! test -x "$(VSINSTALLDIR)/devenv.exe"; then echo "Error: Microsoft Visual Studio .NET is currently required to build MSI and MSM packages"; exit 1; fi
+
+$(MSI_FILE): devenv $(MSM_FILE) addressbook-install.sln addressbook-msi/addressbook-msi.vdproj
 	@rm -f $(MSI_LOG_FILE) $@
 	@CMD='"$(VSINSTALLDIR)/devenv.exe" addressbook-install.sln /build $(DEVENV_CONFIGURATION) /project addressbook-msi /out $(MSI_LOG_FILE)'; \
 	echo $$CMD; \
@@ -45,7 +48,7 @@ $(MSI_FILE): $(MSM_FILE) addressbook-install.sln addressbook-msi/addressbook-msi
 		grep -a "ERROR:" $(MSI_LOG_FILE); \
 	fi
 
-$(MSM_FILE): addressbook addressbook-install.sln addressbook-msm/addressbook-msm.vdproj
+$(MSM_FILE): devenv addressbook addressbook-install.sln addressbook-msm/addressbook-msm.vdproj
 	@rm -f $(MSM_LOG_FILE) $@
 	@CMD='"$(VSINSTALLDIR)/devenv.exe" addressbook-install.sln /build $(DEVENV_CONFIGURATION) /project addressbook-msm /out $(MSM_LOG_FILE)'; \
 	echo $$CMD; \
