Cleaned up the building of packages.
git-svn-id: svn://svn.code.sf.net/p/ifolder/code/trunk@1451 db2431b9-df06-0410-971c-a38ea9a75485

diff --git a/addressbook/package/windows/Makefile.am b/addressbook/package/windows/Makefile.am
--- a/addressbook/package/windows/Makefile.am
+++ b/addressbook/package/windows/Makefile.am
@@ -21,7 +21,7 @@
 #
 #######################################################################
 
-EXTRA_DIST = $(srcdir)/Makefile.am $(srcdir)/addressbook-msi.ism $(srcdir)/addressbook-msm.ism $(srcdir)/addressbook-sdk-msm.ism
+EXTRA_DIST = $(srcdir)/addressbook-msi.ism $(srcdir)/addressbook-msm.ism $(srcdir)/addressbook-sdk-msm.ism
 
 export PKG_CONFIG_PATH := $(PKG_CONFIG_PATH)
 
@@ -45,6 +45,7 @@ MSM_LOG_FILE     = issabld-$(MSM).log
 SDK_MSM_LOG_FILE = issabld-$(SDK_MSM)-msm.log
 
 #ISSABLD = ../../tools/InstallShield/IsSABld.exe
+ISSABLD_DIR := $(shell cygpath --windows `dirname $(ISSABLD)`)
 ISSABLD_CONFIG  = web
 ISSABLD_RELEASE = release
 
@@ -53,24 +54,11 @@ MSI_DISK1     = $(MSI)/$(DISK1)/setup.exe
 MSM_DISK1     = $(MSM)/$(DISK1)/addressbook.msm
 SDK_MSM_DISK1 = $(SDK_MSM)/$(DISK1)/addressbook_sdk.msm
 
-.PHONY: package package-clean
-
-package: $(MSI_FILE)
-
-issabld:
-	@if test -z "$(ISSABLD)"; then \
-		echo ""; \
-		echo "ERROR: environment variable ISSABLD is not set"; \
-		echo ""; \
-		echo "NOTE:  InstallShield is used to build MSI/MSM packages."; \
-		echo "       Set ISSABLD to location of IsSABld.exe."; \
-		echo ""; \
-		exit 1; \
-	fi
+all: $(MSI_FILE)
 
 $(MSI_FILE): issabld $(MSM_FILE) $(SDK_MSM_FILE) $(MSI).ism
 	@rm -f $@ "$(MSI_DISK1)" "$(MSI_LOG_FILE)"
-	@CMD='"$(ISSABLD)" -p "$(MSI).ism" -o "$(MERGE_MODULES_WIN)"'; \
+	@CMD='"$(ISSABLD)" -p "$(MSI).ism" -o "$(ISSABLD_DIR),$(MERGE_MODULES_WIN)"'; \
 		echo $$CMD; \
 		eval $$CMD > "$(MSI_LOG_FILE)" 2>&1; \
 		if test -f "$(MSI_DISK1)"; then \
@@ -116,7 +104,18 @@ $(SDK_MSM_FILE): issabld addressbook-doc $(SDK_MSM).ism
 		echo $$CMD; \
 		eval $$CMD
 
-.PHONY: addressbook-install addressbook addressbook-configure addressbook-dist addressbook-doc
+.PHONY: issabld addressbook-install addressbook addressbook-configure addressbook-dist addressbook-doc
+
+issabld:
+	@if test -z "$(ISSABLD)"; then \
+		echo ""; \
+		echo "ERROR: environment variable ISSABLD is not set"; \
+		echo ""; \
+		echo "NOTE:  InstallShield is used to build MSI/MSM packages."; \
+		echo "       Set ISSABLD to location of IsSABld.exe."; \
+		echo ""; \
+		exit 1; \
+	fi
 
 addressbook-install: addressbook
 	$(MAKE) -C MSI/BUILD/$(PACKAGE)-$(VERSION) install
@@ -138,14 +137,9 @@ addressbook-dist:
 	$(MAKE) -C $(top_srcdir) dist
 
 addressbook-doc: addressbook
-	@if test -x "$(NDOC_CMD)"; then \
-		$(MAKE) -C $(top_srcdir)/doc all; \
-	else \
-		mkdir -p ../../doc/ndoc; \
-		touch ../../doc/ndoc/sdk_doc_was_not_built; \
-	fi
-
-package-clean clean-local:
+	$(MAKE) -C $(top_srcdir)/doc all
+	
+clean:
 	rm -rf $(COMMON_CLEAN_FILES)
 	rm -rf *-setup.exe *.msi *.msm *.log
 	rm -rf MSI
@@ -153,7 +147,7 @@ package-clean clean-local:
 	rm -rf $(MSM)/$(ISSABLD_CONFIG)
 	rm -rf $(SDK_MSM)/$(ISSABLD_CONFIG)
 
-distclean-local: package-clean
+distclean-local:
 	rm -rf $(COMMON_DISTCLEAN_FILES) addressbook.spec
 
 maintainer-clean-local:
diff --git a/simias/package/windows/Makefile.am b/simias/package/windows/Makefile.am
--- a/simias/package/windows/Makefile.am
+++ b/simias/package/windows/Makefile.am
@@ -50,20 +50,7 @@ MSI_DISK1     = $(MSI)/$(DISK1)/setup.exe
 MSM_DISK1     = $(MSM)/$(DISK1)/simias.msm
 SDK_MSM_DISK1 = $(SDK_MSM)/$(DISK1)/simias_sdk.msm
 
-.PHONY: package package-clean
-
-package: $(MSI_FILE)
-
-issabld:
-	@if test -z "$(ISSABLD)"; then \
-		echo ""; \
-		echo "ERROR: environment variable ISSABLD is not set"; \
-		echo ""; \
-		echo "NOTE:  InstallShield is used to build MSI/MSM packages."; \
-		echo "       Set ISSABLD to location of IsSABld.exe."; \
-		echo ""; \
-		exit 1; \
-	fi
+all: $(MSI_FILE)
 
 $(MSI_FILE): issabld $(MSM_FILE) $(SDK_MSM_FILE) $(MSI).ism
 	@rm -f $@ "$(MSI_DISK1)" "$(MSI_LOG_FILE)"
@@ -115,6 +102,17 @@ $(SDK_MSM_FILE): issabld simias-doc $(SDK_MSM).ism
 
 .PHONY: simias-install simias simias-configure simias-dist simias-doc
 
+issabld:
+	@if test -z "$(ISSABLD)"; then \
+		echo ""; \
+		echo "ERROR: environment variable ISSABLD is not set"; \
+		echo ""; \
+		echo "NOTE:  InstallShield is used to build MSI/MSM packages."; \
+		echo "       Set ISSABLD to location of IsSABld.exe."; \
+		echo ""; \
+		exit 1; \
+	fi
+
 simias-install: simias
 	$(MAKE) -C MSI/BUILD/$(PACKAGE)-$(VERSION) install
 	
@@ -135,14 +133,9 @@ simias-dist:
 	$(MAKE) -C $(top_srcdir) dist
 
 simias-doc: simias
-	@if test -x "$(NDOC_CMD)"; then \
-		$(MAKE) -C $(top_srcdir)/doc all; \
-	else \
-		mkdir -p ../../doc/ndoc; \
-		touch ../../doc/ndoc/sdk_doc_was_not_built; \
-	fi
-
-package-clean clean-local:
+	$(MAKE) -C $(top_srcdir)/doc all
+	
+clean:
 	rm -rf $(COMMON_CLEAN_FILES)
 	rm -rf *-setup.exe *.msi *.msm *.log
 	rm -rf MSI
@@ -150,7 +143,7 @@ package-clean clean-local:
 	rm -rf $(MSM)/$(ISSABLD_CONFIG)
 	rm -rf $(SDK_MSM)/$(ISSABLD_CONFIG)
 
-distclean-local: package-clean
+distclean-local:
 	rm -rf $(COMMON_DISTCLEAN_FILES) simias.spec simias-sdk.spec
 
 maintainer-clean-local:
