Converted to build MSI/MSM packages with InstallShield
git-svn-id: svn://svn.code.sf.net/p/ifolder/code/trunk@1349 db2431b9-df06-0410-971c-a38ea9a75485

diff --git a/addressbook/package/windows/Makefile.am b/addressbook/package/windows/Makefile.am
--- a/addressbook/package/windows/Makefile.am
+++ b/addressbook/package/windows/Makefile.am
@@ -20,88 +20,145 @@
 #  Author: Paul Thomas <pthomas@novell.com>
 #
 #######################################################################
-EXTRA_DIST = $(srcdir)/Makefile.am $(srcdir)/addressbook-install.sln $(srcdir)/addressbook-msi/addressbook-msi.vdproj $(srcdir)/addressbook-msm/addressbook-msm.vdproj $(srcdir)/addressbook-sdk-msi/addressbook-sdk-msi.vdproj $(srcdir)/addressbook-sdk-msm/addressbook-sdk-msm.vdproj
+
+EXTRA_DIST = $(srcdir)/Makefile.am $(srcdir)/addressbook-msi.ism $(srcdir)/addressbook-msm.ism $(srcdir)/addressbook-sdk-msm.ism
+
+export PKG_CONFIG_PATH := $(PKG_CONFIG_PATH)
+
+CUR_DIR := $(shell pwd)
+OUT_DIR := $(shell cygpath --windows $(CUR_DIR))
+
+MERGE_MODULES_WIN  := $(shell cygpath --windows "$(USERPROFILE)\My Documents\My InstallShield DevStudio Projects\MergeModules")
+MERGE_MODULES_UNIX := $(shell cygpath --unix "$(USERPROFILE)\My Documents\My InstallShield DevStudio Projects\MergeModules")
 
 RELEASE = 1
-MSI_FILE     = $(PACKAGE)-$(VERSION)-$(RELEASE).msi
+MSI_FILE     = $(PACKAGE)-$(VERSION)-$(RELEASE)-setup.exe
 MSM_FILE     = $(PACKAGE)-$(VERSION)-$(RELEASE).msm
-SDK_MSI_FILE = $(PACKAGE)-sdk-$(VERSION)-$(RELEASE).msi
 SDK_MSM_FILE = $(PACKAGE)-sdk-$(VERSION)-$(RELEASE).msm
-MSI_LOG_FILE     = devenv-addressbook-msi.log
-MSM_LOG_FILE     = devenv-addressbook-msm.log
-SDK_MSI_LOG_FILE = devenv-addressbook-sdk-msi.log
-SDK_MSM_LOG_FILE = devenv-addressbook-sdk-msm.log
 
-.PHONY: package package-sdk package-clean package-install package-uninstall addressbook addressbook-doc devenv
+MSI = addressbook-msi
+MSM = addressbook-msm
+SDK_MSM = addressbook-sdk-msm
 
-all clean:
+MSI_LOG_FILE     = issabld-$(MSI).log
+MSM_LOG_FILE     = issabld-$(MSM).log
+SDK_MSM_LOG_FILE = issabld-$(SDK_MSM)-msm.log
+
+#ISSABLD = ../../tools/InstallShield/IsSABld.exe
+ISSABLD_CONFIG  = web
+ISSABLD_RELEASE = release
+
+DISK1         = $(ISSABLD_CONFIG)/$(ISSABLD_RELEASE)/DiskImages/DISK1
+MSI_DISK1     = $(MSI)/$(DISK1)/setup.exe
+MSM_DISK1     = $(MSM)/$(DISK1)/addressbook.msm
+SDK_MSM_DISK1 = $(SDK_MSM)/$(DISK1)/addressbook_sdk.msm
+
+.PHONY: package package-clean
 
 package: $(MSI_FILE)
 
-package-sdk: package $(SDK_MSI_FILE)
+issabld:
+	@if test -z "$(ISSABLD)"; then \
+		echo ""; \
+		echo "ERROR: environment variable ISSABLD is not set"; \
+		echo ""; \
+		echo "NOTE:  InstallShield is used to build MSI/MSM packages."; \
+		echo "       Set ISSABLD to location of IsSABld.exe."; \
+		echo ""; \
+		exit 1; \
+	fi
 
-addressbook:
-	make -C ../.. all
+$(MSI_FILE): issabld $(MSM_FILE) $(SDK_MSM_FILE) $(MSI).ism
+	@rm -f $@ "$(MSI_DISK1)" "$(MSI_LOG_FILE)"
+	@CMD='"$(ISSABLD)" -p "$(MSI).ism" -o "$(MERGE_MODULES_WIN)"'; \
+		echo $$CMD; \
+		eval $$CMD > "$(MSI_LOG_FILE)" 2>&1; \
+		if test -f "$(MSI_DISK1)"; then \
+			ln "$(MSI_DISK1)" $@; \
+		else \
+			cat "$(MSI_LOG_FILE);" \
+			echo FAILED; exit 1; \
+		fi
+	@test "x" = "x$(INSTALL_PKGS)" || \
+		CMD='cp -f $@ "$(INSTALL_PKGS)"'; \
+		echo $$CMD; \
+		eval $$CMD
+
+$(MSM_FILE): issabld addressbook-install $(MSM).ism
+	@rm -f $@ "$(MSM_DISK1)" "$(MSM_LOG_FILE)"
+	@CMD='"$(ISSABLD)" -p "$(MSM).ism"'; \
+		echo $$CMD; \
+		eval $$CMD > "$(MSM_LOG_FILE)" 2>&1; \
+		if test -f "$(MSM_DISK1)"; then \
+			ln "$(MSM_DISK1)" $@; \
+		else \
+			cat "$(MSM_LOG_FILE)"; \
+			echo FAILED; exit 1; \
+		fi 
+	@mkdir -p "$(MERGE_MODULES_UNIX)"; \
+		CMD='cp -f "$(MSM_DISK1)" "$(MERGE_MODULES_UNIX)"'; \
+		echo $$CMD; \
+		eval $$CMD
+
+$(SDK_MSM_FILE): issabld addressbook-doc $(SDK_MSM).ism
+	@rm -f $@ "$(SDK_MSM_DISK1)" "$(SDK_MSM_LOG_FILE)"
+	@CMD='"$(ISSABLD)" -p "$(SDK_MSM).ism"'; \
+		echo $$CMD; \
+		eval $$CMD > "$(SDK_MSM_LOG_FILE)" 2>&1; \
+		if test -f "$(SDK_MSM_DISK1)"; then \
+			ln "$(SDK_MSM_DISK1)" $@; \
+		else \
+			cat "$(MSM_LOG_FILE)"; \
+			echo FAILED; \
+		fi 
+	@mkdir -p "$(MERGE_MODULES_UNIX)"; \
+		CMD='cp -f "$(SDK_MSM_DISK1)" "$(MERGE_MODULES_UNIX)"'; \
+		echo $$CMD; \
+		eval $$CMD
+
+.PHONY: addressbook-install addressbook addressbook-configure addressbook-dist addressbook-doc
+
+addressbook-install: addressbook
+	$(MAKE) -C MSI/BUILD/$(PACKAGE)-$(VERSION) install
 	
-addressbook-doc:
-	make -C ../../doc all
+addressbook: addressbook-configure
+	$(MAKE) -C MSI/BUILD/$(PACKAGE)-$(VERSION) all
 	
-devenv:
-	@if ! test -x "$(VSINSTALLDIR)/devenv.exe"; then echo "Error: Microsoft Visual Studio .NET is currently required to build MSI and MSM packages"; exit 1; fi
+addressbook-configure: addressbook-dist
+	rm -rf MSI
+	mkdir MSI
+	mkdir -p MSI/BUILD
+	mkdir -p MSI/INSTALL
+	cd MSI/BUILD; \
+		tar -xzf $(CUR_DIR)/$(top_srcdir)/$(PACKAGE)-$(VERSION).tar.gz
+	cd MSI/BUILD/$(PACKAGE)-$(VERSION); \
+		./configure --prefix=$(CUR_DIR)/MSI/INSTALL
+	
+addressbook-dist:
+	$(MAKE) -C $(top_srcdir) dist
 
-ndoc:
-	@if ! test -x "$(NDOC_CMD)"; then echo "Error: You must configure using --with-ndoc-path to build SDK packages"; exit 1; fi
-
-$(MSI_FILE): devenv $(MSM_FILE) addressbook-install.sln addressbook-msi/addressbook-msi.vdproj
-	@rm -f $(MSI_LOG_FILE) $@
-	@CMD='"$(VSINSTALLDIR)/devenv.exe" addressbook-install.sln /build $(DEVENV_CONFIGURATION) /project addressbook-msi /out $(MSI_LOG_FILE)'; \
-	echo $$CMD; \
-	if eval $$CMD; then \
-		mv addressbook-msi/$(DEVENV_CONFIGURATION)/addressbook.msi .; \
-		ln addressbook.msi $@; \
+addressbook-doc: addressbook
+	@if test -x "$(NDOC_CMD)"; then \
+		$(MAKE) -C $(top_srcdir)/doc all; \
 	else \
-		grep -a "ERROR:" $(MSI_LOG_FILE); \
-	fi
-
-$(MSM_FILE): devenv addressbook addressbook-install.sln addressbook-msm/addressbook-msm.vdproj
-	@rm -f $(MSM_LOG_FILE) $@
-	@CMD='"$(VSINSTALLDIR)/devenv.exe" addressbook-install.sln /build $(DEVENV_CONFIGURATION) /project addressbook-msm /out $(MSM_LOG_FILE)'; \
-	echo $$CMD; \
-	if eval $$CMD; then \
-		mv addressbook-msm/$(DEVENV_CONFIGURATION)/addressbook.msm .; \
-		ln addressbook.msm $@; \
-	else \
-		grep -a "ERROR:" $(MSM_LOG_FILE); \
-	fi
-
-$(SDK_MSI_FILE): devenv $(SDK_MSM_FILE) addressbook-install.sln addressbook-sdk-msi/addressbook-sdk-msi.vdproj
-	@rm -f $(SDK_MSI_LOG_FILE) $@
-	@CMD='"$(VSINSTALLDIR)/devenv.exe" addressbook-install.sln /build $(DEVENV_CONFIGURATION) /project addressbook-sdk-msi /out $(SDK_MSI_LOG_FILE)'; \
-	echo $$CMD; \
-	if eval $$CMD; then \
-		mv addressbook-sdk-msi/$(DEVENV_CONFIGURATION)/addressbook-sdk.msi .; \
-		ln addressbook-sdk.msi $@; \
-	else \
-		grep -a "ERROR:" $(SDK_MSI_LOG_FILE); \
-	fi
-
-$(SDK_MSM_FILE): devenv ndoc $(MSM_FILE) addressbook-doc addressbook-install.sln addressbook-sdk-msm/addressbook-sdk-msm.vdproj
-	@rm -f $(SDK_MSM_LOG_FILE) $@
-	@CMD='"$(VSINSTALLDIR)/devenv.exe" addressbook-install.sln /build $(DEVENV_CONFIGURATION) /project addressbook-sdk-msm /out $(SDK_MSM_LOG_FILE)'; \
-	echo $$CMD; \
-	if eval $$CMD; then \
-		mv addressbook-sdk-msm/$(DEVENV_CONFIGURATION)/addressbook-sdk.msm .; \
-		ln addressbook-sdk.msm $@; \
-	else \
-		grep -a "ERROR:" $(SDK_MSM_LOG_FILE); \
+		mkdir -p ../../doc/ndoc; \
+		touch ../../doc/ndoc/sdk_doc_was_not_built; \
 	fi
 
 package-clean clean-local:
-	rm -rf  *.msi *.msm Release Debug */Release */Debug *.log *.suo
+	rm -rf $(COMMON_CLEAN_FILES)
+	rm -rf *-setup.exe *.msi *.msm *.log
+	rm -rf MSI
+	rm -rf $(MSI)/$(ISSABLD_CONFIG)
+	rm -rf $(MSM)/$(ISSABLD_CONFIG)
+	rm -rf $(SDK_MSM)/$(ISSABLD_CONFIG)
 
 distclean-local: package-clean
-	rm -f addressbook.spec
+	rm -rf $(COMMON_DISTCLEAN_FILES) addressbook.spec
 
 maintainer-clean-local:
 	rm -rf $(COMMON_MAINTAINER_CLEAN_FILES)
+
+# do nothing for the following standard targets
+all clean:
 
